### ISSUE TITLE
Error when trying to view Preview build

### ISSUE THREAD

**Issue by fivetwelve** [toitoi-co/toitoi-generate#6]
The preview flow works almost completely except I encounter an error at the end. I am loading what appears to be a valid URL based on API description:

`http://localhost:6557/preview/demo.toitoi.co/65a193e5-18ed-44cc-81a3-5fd67ebb3304/`

Let me know if it points to a deficiency at my end because I'm testing locally, e.g. could the preset not be loaded or available locally?

Error response:

```
{"error":"NotFoundError: No such file exists.
at /Users/fivetwelve/Documents/Projects/Work/Schmopera/toitoi/toitoi-generate/libs/generator.js:243:11
at Layer.handle_error (/Users/fivetwelve/Documents/Projects/Work/Schmopera/toitoi/toitoi-generate/node_modules/express/lib/router/layer.js:71:5)
at trim_prefix (/Users/fivetwelve/Documents/Projects/Work/Schmopera/toitoi/toitoi-generate/node_modules/express/lib/router/index.js:310:13)
at /Users/fivetwelve/Documents/Projects/Work/Schmopera/toitoi/toitoi-generate/node_modules/express/lib/router/index.js:280:7
at Function.process_params (/Users/fivetwelve/Documents/Projects/Work/Schmopera/toitoi/toitoi-generate/node_modules/express/lib/router/index.js:330:12)
at next (/Users/fivetwelve/Documents/Projects/Work/Schmopera/toitoi/toitoi-generate/node_modules/express/lib/router/index.js:271:10)
at /Users/fivetwelve/Documents/Projects/Work/Schmopera/toitoi/toitoi-generate/node_modules/express/lib/router/index.js:618:15
at next (/Users/fivetwelve/Documents/Projects/Work/Schmopera/toitoi/toitoi-generate/node_modules/express/lib/router/index.js:256:14)
at /Users/fivetwelve/Documents/Projects/Work/Schmopera/toitoi/toitoi-generate/node_modules/express/lib/response.js:417:7
at SendStream.onerror (/Users/fivetwelve/Documents/Projects/Work/Schmopera/toitoi/toitoi-generate/node_modules/express/lib/response.js:993:5)
at emitOne (events.js:77:13)
at SendStream.emit (events.js:169:7)
at SendStream.error (/Users/fivetwelve/Documents/Projects/Work/Schmopera/toitoi/toitoi-generate/node_modules/send/index.js:245:17)
at SendStream.onStatError (/Users/fivetwelve/Documents/Projects/Work/Schmopera/toitoi/toitoi-generate/node_modules/send/index.js:356:12)
at next (/Users/fivetwelve/Documents/Projects/Work/Schmopera/toitoi/toitoi-generate/node_modules/send/index.js:658:28)
at /Users/fivetwelve/Documents/Projects/Work/Schmopera/toitoi/toitoi-generate/node_modules/send/index.js:666:23
at FSReqWrap.oncomplete (fs.js:82:15)"}
```

**Comment by fivetwelve** [comment]
Error was caused by theme files not available on the server for rendering. Even when testing it is preferable to select the user's preset through the -cms UI rather than updating the value in -admin interface so that the selection triggers the retrieval of the theme from remote server and its unpacking/installation.
